version: '1'
services:
  bot:
    container_name: 'hmstr'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1 -m n"
    volumes:
      - .:/app
